name: crawler_detector
description: Helps detecting web crawlers.
version: 0.0.1
repository: https://github.com/yjbanov/crawler_detector

environment:
  sdk: ^3.4.0-138.0.dev

dependencies:
  web: ">=0.5.0 <1.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
