name: crawler_detector
description: >-
  Functions for detecting user agents that are web crawlers, such as search
  engines, ad systems, and more, which can help optimizing the app for better
  crawlability.
version: 0.0.1
repository: https://github.com/yjbanov/crawler_detector

environment:
  sdk: ^3.3.0

dependencies:
  web: ">=0.5.0 <1.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
